[package]
name = "animalsiknow-github-io"
version = "0.1.0"
authors = ["Simon Génier <1782845+animalsiknow@users.noreply.github.com>"]
homepage = "https://animalsiknow.github.io/"

[dependencies.ei-sys]
version = "0.7.0"

[dependencies.mri-sys]
git = "https://github.com/animalsiknow/mri-sys"
